### PR TITLE
chore(ci): include node 14 and 15 in `tests`

### PR DESCRIPTION
**Pull request by jef**
### Description

Includes latest node version in tests.

### CODE REVIEW

**Comment by jef** [comment]
Sorry in advance for the ping @lgarron, but do we want to maintain this?

Thanks!

**Comment by jef** [comment]
I'm thinking in another PR we also could deprecate travis-ci and use actions.

**Comment by lgarron** [comment]
> Sorry in advance for the ping @lgarron, but do we want to maintain this?

We do still have an important use for it, so I think we should!

**Comment by lgarron** [comment]
> I'm thinking in another PR we also could deprecate travis-ci and use actions.

I don't have a lot of time for this, but I'd be happy to review that!

**Comment by jef** [comment]
Alright, I think it's ready. If you have any concerns about how often it's building, we can change that.

As well as the node versions. Not sure how many versions you want to run. Perhaps just LTS and latest.

**Review by lgarron — APPROVED** [review]
`ci` is a more generic name than `tests`, but looks good to me!

**Comment by jef** [comment]
I don't mind changing to `build and tests` or something. Up to you.

**Comment by lgarron** [comment]
> I don't mind changing to `build and tests` or something. Up to you.

I'm a fan of naming things what they are/do as specifically as possible (if it's not too verbose), so I think this would be worth it! :-D

**Comment by jef** [comment]
Alright! Updated. One last thing. Did you want _all_ these versions running or would you like it slimmed up?

**Pull request closed without merging**
